In [112]:
from sqlalchemy import create_engine
import pandas as pd

In [113]:
# Parámetros de conexión
user     = 'root'
password = 'password'
sqlServer = 'localhost' # debería ser IP o DNS del servidor de la base de datos

# Creamos string de conexión
connStr = "mysql+mysqlconnector://" + user + ":" + password + "@" + sqlServer 

# print de string de conexión
print (connStr)

# Conectamos con el servidor
conn = create_engine(connStr).connect()

mysql+mysqlconnector://root:password@localhost

In [114]:
conn.execute("CREATE DATABASE idealista")

In [115]:
conn.execute("USE idealista")

In [116]:
df_agencias = pd.read_csv("agencias (1).csv")
df_agencias

   AGENCY_ID          AGENCY_NAME  RATING
0          1  Agencia Madrid Plus     4.5
1          2     Madrid Viviendas     4.2
2          3   Madrid Propiedades     4.8
3          4  Madrid Casas Deluxe     4.7
4          5     Inmo Casa Madrid     4.1

In [117]:
from sqlalchemy import Integer, String, Float
dtypes = {"AGENCY_ID":Integer,
          "AGENCY_NAME":String(100),
          "RATING":Float}
df_agencias.to_sql("agencias", conn, index=False, dtype=dtypes)

5

In [118]:
conn.execute("ALTER TABLE agencias ADD PRIMARY KEY(AGENCY_ID)")

In [119]:
df_ddbb_idealista = pd.read_csv("dataset_idealista_madrid.csv")
df_ddbb_idealista

,Unnamed: 0,ASSETID,PERIOD,PRICE,UNITPRICE,CONSTRUCTEDAREA,ROOMNUMBER,BATHNUMBER,HASTERRACE,HASLIFT,...,CADASTRALQUALITYID,BUILTTYPEID_1,BUILTTYPEID_2,BUILTTYPEID_3,DISTANCE_TO_CITY_CENTER,DISTANCE_TO_METRO,DISTANCE_TO_CASTELLANA,LONGITUDE,LATITUDE,AGENCY_ID
0,0,A15019136831406238029,201803,126000.0,2680.851064,47,1,1,0,1,...,3.0,0,1,0,8.058429,0.872075,6.868677,-3.766933,40.362485,3
1,1,A6677225905472065344,201803,235000.0,4351.851852,54,1,1,0,0,...,3.0,0,0,1,0.876369,0.116382,1.544125,-3.710725,40.422430,5
2,2,A13341979748618524775,201803,373000.0,4973.333333,75,2,1,0,0,...,3.0,0,0,1,0.907479,0.139109,1.608444,-3.711571,40.422190,2
3,3,A4775182175615276542,201803,284000.0,5916.666667,48,1,1,0,1,...,5.0,0,0,1,0.845462,0.144299,1.516166,-3.710440,40.422251,4
4,4,A2492087730711701973,201803,228000.0,4560.000000,50,0,1,0,0,...,7.0,0,0,1,1.250231,0.337098,1.794136,-3.714340,40.408741,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94810,94810,A3962186799478940177,201812,347000.0,3017.391304,115,3,2,1,1,...,3.0,0,0,1,10.003059,0.866826,8.276950,-3.592154,40.445810,2
94811,94811,A3876164367053781729,201812,311000.0,3344.086022,93,2,2,0,1,...,3.0,0,0,1,10.198147,1.019788,8.496364,-3.589376,40.445013,4
94812,94812,A17768295786772492698,201803,342000.0,2826.446281,121,2,2,1,1,...,3.0,0,0,1,11.204027,1.883650,9.573127,-3.576271,40.443196,4
94813,94813,A15733144649359668635,201806,146000.0,2354.838710,62,3,1,0,0,...,5.0,0,0,1,8.780692,0.171736,6.941217,-3.608694,40.447931,1
94814,94814,A9716488392839016117,201812,334000.0,3591.397849,93,3,1,1,1,...,5.0,0,0,1,11.070417,0.212377,8.799697,-3.585056,40.458098,4

In [120]:
from sqlalchemy import Integer, String, Float
dtypes = {
    "ASSETID": String(100),
    "PERIOD": Integer,
    "PRICE": Float,
    "UNITPRICE": Float,
    "CONSTRUCTEDAREA": Integer,
    "ROOMNUMBER": Integer,
    "BATHNUMBER": Integer,
    "HASTERRACE": Integer,
    "HASLIFT": Integer,
    "HASAIRCONDITIONING": Integer,
    "HASPARKINGSPACE": Integer,
    "ISPARKINGSPACEINCLUDEDINPRICE": Integer,
    "HASNORTHORIENTATION": Integer,
    "HASSOUTHORIENTATION": Integer,
    "HASEASTORIENTATION": Integer,
    "HASWESTORIENTATION": Integer,
    "HASBOXROOM": Integer,
    "HASWARDROBE": Integer,
    "HASSWIMMINGPOOL": Integer,
    "HASDOORMAN": Integer,
    "HASGARDEN": Integer,
    "ISDUPLEX": Integer,
    "ISSTUDIO": Integer,
    "ISINTOPFLOOR": Integer,
    "CONSTRUCTIONYEAR": Integer,
    "CADCONSTRUCTIONYEAR": Integer,
    "CADMAXBUILDINGFLOOR": Integer,
    "CADDWELLINGCOUNT": Integer,
    "CADASTRALQUALITYID": Integer,
    "BUILTTYPEID_1": Integer,
    "BUILTTYPEID_2": Integer,
    "BUILTTYPEID_3": Integer,
    "DISTANCE_TO_CITY_CENTER": Float,
    "DISTANCE_TO_METRO": Float,
    "DISTANCE_TO_CASTELLANA": Float,
    "LONGITUDE": Float,
    "LATITUDE": Float,
    "AGENCY_ID": Integer,
}


df_ddbb_idealista.to_sql("viviendas", conn, index=False, dtype=dtypes)

94815

In [121]:
conn.execute("ALTER TABLE viviendas ADD FOREIGN KEY (AGENCY_ID) REFERENCES agencias(AGENCY_ID)")

### PRIMERA PARTE
1

In [122]:
pd.read_sql("""SELECT ASSETID, BATHNUMBER, HASLIFT, HASPARKINGSPACE, PRICE 
FROM viviendas 
WHERE BATHNUMBER >=2
AND HASLIFT = 1
AND HASPARKINGSPACE = 1""", conn)

                     ASSETID  BATHNUMBER  HASLIFT  HASPARKINGSPACE      PRICE
0       A3694300518337702967           3        1                1  3187000.0
1      A17297754155641241826           3        1                1  1131000.0
2       A4444264986115631121           2        1                1   943000.0
3       A3581405731630543117           6        1                1  1939000.0
4       A6349776121498293972           2        1                1   369000.0
...                      ...         ...      ...              ...        ...
15994   A7034851435465452892           2        1                1   229000.0
15995  A10324853219120899544           2        1                1   293000.0
15996   A3962186799478940177           2        1                1   347000.0
15997   A3876164367053781729           2        1                1   311000.0
15998  A17768295786772492698           2        1                1   342000.0

[15999 rows x 5 columns]

###
2

In [123]:
pd.read_sql("""SELECT AVG(PRICE) AS "Precio medio viviendas con terraza"
FROM viviendas
WHERE HASTERRACE = 1""", conn)

   Precio medio viviendas con terraza
0                       432226.665479

###
3.1 Y 3.2 (No encontre la manera de hacerlo en una sola query)

In [124]:
pd.read_sql("""SELECT ROOMNUMBER, COUNT(*)
FROM viviendas
GROUP BY ROOMNUMBER
ORDER BY ROOMNUMBER;""",conn)

    ROOMNUMBER  COUNT(*)
0            0      2745
1            1     13338
2            2     28422
3            3     33961
4            4     11674
5            5      3350
6            6       789
7            7       279
8            8       142
9            9        35
10          10        24
11          11        16
12          12        18
13          13         6
14          14         5
15          15         3
16          16         2
17          18         2
18          20         2
19          33         1
20          93         1

In [125]:
pd.read_sql("""SELECT ROOMNUMBER, AVG(PRICE) as "Precio medio por número de habitación"
            FROM viviendas
            GROUP BY ROOMNUMBER 
            ORDER BY ROOMNUMBER;""",conn)

    ROOMNUMBER  Precio medio por número de habitación
0            0                           2.211089e+05
1            1                           2.402881e+05
2            2                           2.847405e+05
3            3                           3.492892e+05
4            4                           6.932969e+05
5            5                           1.114953e+06
6            6                           1.431944e+06
7            7                           1.442634e+06
8            8                           1.591268e+06
9            9                           1.212971e+06
10          10                           2.079083e+06
11          11                           1.799938e+06
12          12                           1.916667e+06
13          13                           2.337333e+06
14          14                           1.980000e+06
15          15                           2.164333e+06
16          16                           2.665500e+06
17          18                           4.219500e+06
18          20                           1.435000e+06
19          33                           1.090000e+05
20          93                           4.500000e+05

###
4

In [126]:
pd.read_sql("""SELECT ASSETID, PRICE ,CONSTRUCTEDAREA
FROM viviendas
WHERE PRICE> (SELECT AVG(PRICE) FROM viviendas)""",conn)

                     ASSETID      PRICE  CONSTRUCTEDAREA
0      A18372428154681111419   498000.0              127
1       A9587449507628658013   425000.0               70
2       A3694300518337702967  3187000.0              360
3      A11532129615377606790   422000.0              114
4       A2893199643597593313  1013000.0              155
...                      ...        ...              ...
29694   A3107360537414270361   936000.0              205
29695  A10395827789147723674   460000.0              115
29696  A12819204236902632452   460000.0               93
29697  A13569164165299053978   457000.0               93
29698   A7764751834904574987   426000.0               94

[29699 rows x 3 columns]

###
5

In [127]:
pd.read_sql("""SELECT COUNT(*) AS "Total viviendas"
FROM viviendas
WHERE ROOMNUMBER > 3
AND ISINTOPFLOOR = 1""", conn)

   Total viviendas
0              356

###
6

In [128]:
pd.read_sql("""SELECT ASSETID AS "Propiedad más cara"
FROM viviendas 
ORDER BY PRICE DESC
LIMIT 1""",conn)

      Propiedad más cara
0  A17400384699956653141

###
7

In [129]:
pd.read_sql("""SELECT AVG(DISTANCE_TO_CITY_CENTER) AS "Distancia media al centro"
FROM viviendas
WHERE CONSTRUCTIONYEAR > 2000""",conn)

   Distancia media al centro
0                   6.549824

###
8

In [130]:
pd.read_sql("""SELECT COUNT(*) AS "Total propiedades"
FROM viviendas
WHERE HASSWIMMINGPOOL = 1
AND HASGARDEN = 1
AND HASPARKINGSPACE = 1
""", conn)

   Total propiedades
0               9034

### NOTA: Se ha hecho el porcentaje de entre las propiedades totales de segunda mano, no de todo el dataset.
9.

In [131]:
pd.read_sql("""SELECT (COUNT(*)/(SELECT COUNT(*) FROM viviendas WHERE BUILTTYPEID_1 = 0)) *100 AS "Porcentaje de viviendas"
FROM viviendas
WHERE BUILTTYPEID_3 = 1
AND BATHNUMBER > 2""",conn)

   Porcentaje de viviendas
0                   7.6121

10.

### Se ve una ligera tendencia hacia precios mas bajos en los meses de junio y septiembre con minimos de 21mil y 24mil respectivamente. Mientras que en los meses de marzo y diciembre los precios son un poco mas altos con maximos superando los 6 y 8 millones respectivamente.

In [132]:
pd.read_sql("""SELECT 
    PERIOD,
    AVG(PRICE) AS precio_medio,
    MAX(PRICE) AS precio_maximo,
    MIN(PRICE) AS precio_minimo
FROM viviendas
WHERE PERIOD BETWEEN 201801 AND 201812
GROUP BY PERIOD
ORDER BY PERIOD;""", conn)

   PERIOD   precio_medio  precio_maximo  precio_minimo
0  201803  404960.766423      6729000.0        32000.0
1  201806  367527.505533      7138000.0        21000.0
2  201809  365467.225944      6829000.0        24000.0
3  201812  410952.654168      8133000.0        24000.0

###
11

In [133]:
conn.execute("""UPDATE viviendas 
SET PRICE = PRICE * 1.05
WHERE HASAIRCONDITIONING = 1""")

###
12

In [134]:
conn.execute("""DELETE FROM viviendas 
WHERE CONSTRUCTEDAREA < 30""")

### 
13

In [135]:
conn.execute("""
CREATE VIEW viviendas_terraza_piscina AS
SELECT ASSETID, PRICE, ROOMNUMBER, BATHNUMBER
FROM viviendas
WHERE HASTERRACE = 1
  AND HASSWIMMINGPOOL = 1
""")

###
14

In [136]:
pd.read_sql("""SELECT
AVG(CASE WHEN HASSOUTHORIENTATION = 1 THEN PRICE / CONSTRUCTEDAREA END) AS precio_promedio_sur,
AVG(CASE WHEN HASEASTORIENTATION = 1 THEN PRICE / CONSTRUCTEDAREA END) AS precio_promedio_este,
AVG(CASE WHEN HASWESTORIENTATION = 1 THEN PRICE / CONSTRUCTEDAREA END) AS precio_promedio_oeste
FROM viviendas;""",conn)

   precio_promedio_sur  precio_promedio_este  precio_promedio_oeste
0          3906.409165           3886.469119            4033.735424

###
15

In [137]:
pd.read_sql("""SELECT
AVG(CASE WHEN HASPARKINGSPACE = 1 THEN PRICE END) - 
AVG(CASE WHEN HASPARKINGSPACE = 0 THEN PRICE END) AS "diferencia_precio_promedio"
FROM viviendas;""",conn)

   diferencia_precio_promedio
0               227141.183849

### SEGUNDA PARTE
INNER JOIN PARA TRABAJAR CON AMBAS COLUMNAS

In [141]:
conn.execute("""CREATE VIEW agencia_viviendas AS
SELECT v.*, a.AGENCY_NAME, a.RATING 
FROM viviendas AS v
INNER JOIN agencias AS a 
ON v.AGENCY_ID = a.AGENCY_ID;""")

###
1

In [142]:
pd.read_sql("""SELECT *
FROM agencia_viviendas
WHERE AGENCY_ID IS NOT NULL
AND HASSWIMMINGPOOL = 1
AND HASPARKINGSPACE = 1;""", conn)

,Unnamed: 0,ASSETID,PERIOD,PRICE,UNITPRICE,CONSTRUCTEDAREA,ROOMNUMBER,BATHNUMBER,HASTERRACE,HASLIFT,...,BUILTTYPEID_2,BUILTTYPEID_3,DISTANCE_TO_CITY_CENTER,DISTANCE_TO_METRO,DISTANCE_TO_CASTELLANA,LONGITUDE,LATITUDE,AGENCY_ID,AGENCY_NAME,RATING
0,155,A4671190715338907020,201803,949000.0,5894.41,161,3,3,0,1,...,0,1,0.610905,0.116534,1.342640,-3.70884,40.4205,2,Madrid Viviendas,4.2
1,976,A13321527061841065076,201803,132300.0,840.00,150,4,2,1,1,...,0,1,1.193540,0.299821,0.415795,-3.69826,40.4067,3,Madrid Propiedades,4.8
2,1487,A7976691527475320095,201803,578550.0,4591.67,120,2,2,0,1,...,0,1,1.374820,0.066166,1.848350,-3.71266,40.4269,4,Madrid Casas Deluxe,4.7
3,1627,A14703419175734607889,201803,582750.0,4625.00,120,2,2,0,1,...,0,1,1.340620,0.122868,1.792580,-3.71199,40.4269,4,Madrid Casas Deluxe,4.7
4,1639,A3347762916822626363,201803,452000.0,3013.33,150,3,3,1,1,...,0,1,1.055790,0.064050,0.938890,-3.70180,40.4260,1,Agencia Madrid Plus,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10827,94807,A10324853219120899544,201812,307650.0,2738.32,107,3,2,0,1,...,0,1,8.476250,0.501479,7.327070,-3.60613,40.4002,5,Inmo Casa Madrid,4.1
10828,94808,A8974485819301533463,201812,205800.0,5939.39,33,0,1,0,1,...,0,1,6.549840,0.554890,4.857430,-3.63144,40.4373,4,Madrid Casas Deluxe,4.7
10829,94810,A3962186799478940177,201812,364350.0,3017.39,115,3,2,1,1,...,0,1,10.003100,0.866826,8.276950,-3.59215,40.4458,2,Madrid Viviendas,4.2
10830,94811,A3876164367053781729,201812,326550.0,3344.09,93,2,2,0,1,...,0,1,10.198100,1.019790,8.496360,-3.58938,40.4450,4,Madrid Casas Deluxe,4.7
10831,94812,A17768295786772492698,201803,359100.0,2826.45,121,2,2,1,1,...,0,1,11.204000,1.883650,9.573130,-3.57627,40.4432,4,Madrid Casas Deluxe,4.7

###
2

In [144]:
pd.read_sql("""SELECT ASSETID, AGENCY_NAME,PRICE,RATING
FROM agencia_viviendas 
WHERE RATING > 4.5""", conn)

                     ASSETID          AGENCY_NAME      PRICE  RATING
0      A15019136831406238029   Madrid Propiedades   132300.0     4.8
1      A18372428154681111419   Madrid Propiedades   498000.0     4.8
2      A15416265623565967313   Madrid Propiedades   211000.0     4.8
3       A2893199643597593313   Madrid Propiedades  1013000.0     4.8
4      A10976273205185897585   Madrid Propiedades  2466450.0     4.8
...                      ...                  ...        ...     ...
37793   A9237634521852306074  Madrid Casas Deluxe   149100.0     4.7
37794   A8974485819301533463  Madrid Casas Deluxe   205800.0     4.7
37795   A3876164367053781729  Madrid Casas Deluxe   326550.0     4.7
37796  A17768295786772492698  Madrid Casas Deluxe   359100.0     4.7
37797   A9716488392839016117  Madrid Casas Deluxe   350700.0     4.7

[37798 rows x 4 columns]

### DUDA: ¿La pregunta 3 se haría así o con un left join?
3

In [147]:
pd.read_sql("""SELECT DISTINCT AGENCY_ID, AGENCY_NAME
            FROM agencia_viviendas""",conn)

   AGENCY_ID          AGENCY_NAME
0          1  Agencia Madrid Plus
1          2     Madrid Viviendas
2          3   Madrid Propiedades
3          4  Madrid Casas Deluxe
4          5     Inmo Casa Madrid

### Todas las agencias aparecen en el dataset asi que tienen propiedades todas.

### 
4

In [153]:
pd.read_sql("""SELECT AGENCY_NAME, AVG(PRICE) AS "Media de precio"
            FROM agencia_viviendas
            GROUP BY AGENCY_NAME
            ORDER BY AVG(PRICE) DESC
            LIMIT 1
            """, conn)

        AGENCY_NAME  Media de precio
0  Inmo Casa Madrid    416531.602454

###
5

In [161]:
pd.read_sql("""SELECT v.ASSETID, a.AGENCY_NAME
FROM viviendas AS v
LEFT JOIN agencias AS a
ON v.AGENCY_ID = a.AGENCY_ID;""", conn)

                     ASSETID          AGENCY_NAME
0      A15019136831406238029   Madrid Propiedades
1       A6677225905472065344     Inmo Casa Madrid
2      A13341979748618524775     Madrid Viviendas
3       A4775182175615276542  Madrid Casas Deluxe
4       A2492087730711701973  Agencia Madrid Plus
...                      ...                  ...
93893   A3962186799478940177     Madrid Viviendas
93894   A3876164367053781729  Madrid Casas Deluxe
93895  A17768295786772492698  Madrid Casas Deluxe
93896  A15733144649359668635  Agencia Madrid Plus
93897   A9716488392839016117  Madrid Casas Deluxe

[93898 rows x 2 columns]

###
6

In [172]:
pd.read_sql("""SELECT AGENCY_NAME, COUNT(*) AS "Total propiedades"
FROM agencia_viviendas
GROUP BY AGENCY_NAME
ORDER BY 2 DESC
""", conn)

           AGENCY_NAME  Total propiedades
0   Madrid Propiedades              19042
1  Agencia Madrid Plus              18955
2  Madrid Casas Deluxe              18756
3     Inmo Casa Madrid              18584
4     Madrid Viviendas              18561

In [173]:
# Cerramos conexión con el servidor
conn.close()